### ISSUE TITLE
Can we have an uninstall command

### ISSUE THREAD

**Issue by alecgregory** [beezwax/bzBond#10]
Not as high a priority as getting plug-ins working. But at some point I'd like to explore an uninstall script.

**Comment by gosukiwi** [comment]
There's an uninstall script already :P just replace `install.sh` with `uninstall.sh`

**Comment by alecgregory** [comment]
I thought I'd seen it but didn't see it in the readme!

**Comment by gosukiwi** [comment]
Yeah my bad, I forgot to update the README, I'll add some info
