### ISSUE TITLE
On macOS scripts in the bin folder don't have execute permissions

### ISSUE THREAD

**Issue by alecgregory** [beezwax/bzBond#18]
After a macOS install the scripts in the `bin` folder have the following permissions so can't be run by any user:

```
-rw-r--r--  1 root  wheel   477 Mar  7 20:50 create-plugin.sh
-rw-r--r--  1 root  wheel   266 Mar  7 20:50 install-plugin.sh
-rw-r--r--  1 root  wheel  2995 Mar  7 20:50 install.sh
-rw-r--r--  1 root  wheel   718 Mar  7 20:50 uninstall.sh
```

**Comment by gosukiwi** [comment]
Tested this using Simcloud and little hack to be able to have `node` and `npm` where the FileMaker server's version would be, and seems to be working (using Ventura). Also works in Ubuntu (testing for regressions).
