### ISSUE TITLE
bzBond-server update process

### ISSUE THREAD

**Issue by alecgregory** [beezwax/bzBond#25]
It would be good to be able to update bzBond-server to the latest version without losing installed microbonds (which I assume it what would happen if we just did a git pull).

My rough idea for this would be a script that downloads the latest version to a temp folder and then replaces all files except for `microbonds.js` file and the `installed-microbonds` folder. Other files that might support microbonds (e.g. credentials) would be left alone too.

**Comment by alecgregory** [comment]
@gosukiwi thoughts?

**Comment by gosukiwi** [comment]
Interesting, I think my approach would be the opposite, just backup the `microbonds.js` file, do a `git pull`, then replace it. The `git pull` command won't replace the contents of the `microbonds` folder.
