### ISSUE TITLE
macOS installation issues

### ISSUE THREAD

**Issue by alecgregory** [beezwax/bzBond#6]
I tried the installer on a macOS server (Monterey) and it went pretty well, there were just a few issues

1) I don't think the `root` group exists on macOS because for the line
`sudo chown -R root:root /var/www/bzbond-server`
gives the error
`chown: root: illegal group name`

2) The app is not launching after install. I am not sure which of the following lines is problematic
```
launchctl load /Library/LaunchDaemons/net.beezwax.bzbond-server.plist
launchctl start net.beezwax.bzbond-server
```
But the terminal output related to the launch
```
Warning: Expecting a LaunchAgents path since the command was ran as user. Got LaunchDaemons instead.
`launchctl bootstrap` is a recommended alternative.
```

I manually ran the commands as sudo and that worked. So I guess we either change the script to run as sudo or try the `launchctl bootstrap` recommendation from the output

**Comment by gosukiwi** [comment]
I updated the macOS script and tried it on Monterey, it seems to be working now. I'd like confirmation from you before closing this issue though :P @alecgregory

**Comment by alecgregory** [comment]
Initial install now works
